name: docker

on:
  push:
    branches-ignore:
      - 'dependabot/*'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: beerchat/beerchat
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true
